apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-underwriting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credit-underwriting
  template:
    metadata:
      labels:
        app: credit-underwriting
    spec:
      containers:
      - name: credit-underwriting
        image: credit-underwriting:latest
        ports:
        - containerPort: 5004
        env:
        - name: MONGO_URI
          value: mongodb://mongo:27017/
---
apiVersion: v1
kind: Service
metadata:
  name: credit-underwriting
spec:
  selector:
    app: credit-underwriting
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004